### ISSUE TITLE
Action Bar, Titles, Boss Bar, PvP stats

### ISSUE THREAD

**Issue by car1ot** [ChanceSD/PvPManager#183]
I very like your plugin, it is incredible!
But chat messages notifications is kind of old-school and there could be more functions in plugin.

Please, could you add:
1. Optional Action Bar timer with message "PvP will end in 3.2.1... sec".
2. Optional Titles with messages "You entered PvP", "You left PvP".
3. Optional Boss Bar with message "PvP will end in 3.2.1... sec".
4. Optional PvP stats with Placeholder API or own scoreboard.

I can't find any pvp stats placeholders for 1.15 server.

Thanks.

**Comment by NoChanceSD** [comment]
I agree with you, the plugin was barely worked on during 2017 and 2018 so it's missing some new features like those, i have been updating it to get it up to speed.

The action bar is a planned feature but while it's added you can use this: https://www.spigotmc.org/resources/combatactionbar.12923/ together with PvPManager, it worked fine last time i tried.
The other features will come after but PvP stats will probably take longer to implement and likely just on the premium version.

**Comment by car1ot** [comment]
Okay, thanks
