### ISSUE TITLE
Please cancel teleport events from CMI (Tp/back etc)

### ISSUE THREAD

**Issue by TomLewis** [ChanceSD/PvPManager#209]
CMI is a premium version of essentials that has a better teleport system /tpahere etc: https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

I have used it for a bit now, but theres a slight issue where PvPManager isnt canceling the Tp request once its been accepted before getting tagged in PvP
Please can you support all CMI teleport hooks.

https://www.youtube.com/watch?v=3eun9RkD13s&feature=youtu.be

**Comment by NoChanceSD** [comment]
I believe this was fixed by CMI, see the issue I made: https://github.com/Zrips/CMI/issues/3371 
Don't know which CMI version you are using but try updating to the latest.
The premium version is also more aggressive at blocking teleports but I believe it's working fine on the free one too.

**Comment by FrozenBeard** [comment]
I am using the latest CMI, but im using Paper 1.12.2 if that makes it different?

**Comment by NoChanceSD** [comment]
I doubt there would be a difference on 1.12.2 but it's possible, I know for sure it's working on paper 1.15.2 using "/cmi tpahere" though, tested it yesterday.
