### ISSUE TITLE
Pvp protection after death issue. 

### ISSUE THREAD

**Issue by Ellendyra** [ChanceSD/PvPManager#211]
I have it set up to protect a player from pvp for 15 seconds after their death and its plays out more like 2 minutes. Also during that time they can still pvp other players which doesn't seem right either.

**Comment by NoChanceSD** [comment]
Just to make sure do you see any message in chat like "player has respawn protection" or "you have respawn protection"? 
If you don't, it might be another plugin blocking pvp. I can't really reproduce this issue, I tried setting it to 15 seconds and it worked correctly for both players.
