### ISSUE TITLE
PvP in WordGuard Region

### ISSUE THREAD

**Issue by XragonX147** [ChanceSD/PvPManager#238]
Hello,

I have a WordGuard Region with no PvP allowed.
If a Player got hit befor he is in this region the has 10 seconds he can enter the NoPvP Region and can kill every player inside.

**To Reproduce**
1. Enable Tagged In Combat:
2. Hit a Player Outside the Region,so he has the 10 seconds Combat Timer
3. Let the Player run in the NoPvP Zone, now he can kill everybody for 10 seconds

**Expected behavior**
PvPManager should respect other NoPvP Zones

**Plugin and Server version**
Plugin: 3.7.16
Server: 1.16.5 Paper #498

Thanks.

**Comment by ChanceSD** [comment]
This is a feature from the plugin, you can disable it by setting vulnerable to false in the config.
