### ISSUE TITLE
permission node to bypass respawn protection when killed per player

### ISSUE THREAD

**Issue by LcorpOfficial** [ChanceSD/PvPManager#239]
**Is your feature request related to a problem? Please describe.**

this is good for PVP worldguard regions or specific players.

**Describe the solution you'd like**

would like for specific players to not receive respawn protection even if enabled in config by permission.

**Comment by TomLewis** [comment]
Be good to have a worldguard exception for this too for arena's.

**Comment by ChanceSD** [comment]
Added the permission, although ideally would like to have a worldguard flag instead.

**Comment by TomLewis** [comment]
GG! Would this be possible to add a custom WG flag later on?

**Comment by ChanceSD** [comment]
Yes, should probably be on a separate ticket. I already have that feature planned though so not necessary to make a new one.
