### ISSUE TITLE
Worldguard exception for multiple kill punishment

### ISSUE THREAD

**Issue by TomLewis** [ChanceSD/PvPManager#242]
I have an arena in my survival that has keep inventory on, I would like to disable the PvP multi kill protection for this one worldguard claim. 

The PvP protection is fantastic outside the arena as it stops people getting killed over and over, I just jail them.
Not so good for an arena!

**Comment by ChanceSD** [comment]
I added worldguard exclusions for the kill abuse section in the premium version a while back, forgot to close this.
