### ISSUE TITLE
Timed PvP | Residence SafeZone Support

### ISSUE THREAD

**Issue by corexti** [ChanceSD/PvPManager#246]
### Timed PvP Disable
- I've realised that after newbie protection expires you can't give people back newbie protection, therefore I can't protect my players from PvP in any other way. So I thought of this feature as disabling PvP for specific players for x-minutes.
- Example: **/pvptimed {player} {minutes}** After which expires the player goes back into PvP true mode.
 
I think in general this would be a good idea to give access to players to more features and more protection.

### Residence SafeZone Support
- Now I noticed there is a safe zone support in the config but this doesn't work for Residence plugin. People can run away in safe zones and they don't get pushed either.

**Comment by ChanceSD** [comment]
About the timed pvp disable, the premium version already has pretty much that feature, it's called /pvpgrant and it protects for x time.
For Residence support, the vulnerable option should work for Residence as well, pushing back would require specific support though and currently I don't have plans to add specific support for other region plugins.
