### ISSUE TITLE
Glowing effect

### ISSUE THREAD

**Issue by WilsonChoong** [ChanceSD/PvPManager#258]
Because for some reason I decide to delete PvPManger Plugin from my 1.17 server. However, player doesn't loses the glowing effect. What can I do to get rid of it?

**Comment by ChanceSD** [comment]
This was a Spigot bug that didn't allow to remove glowing: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/bc835ae644c0d87277cff647c245f43c43654c29
To put it back you need to update Spigot and then use PvPManager to tag the player and let it untag so it removes the glow. Or search for some glow plugin and try to remove glow with that but will also require a Spigot update first.

**Comment by WilsonChoong** [comment]
But my spigot jar file is 1.17 version

**Comment by ChanceSD** [comment]
I know, but it needs to be updated to the newest version.

**Comment by WilsonChoong** [comment]
how do i do it?

**Comment by ChanceSD** [comment]
How did you get the Spigot you are using now? Use the same way but do it again to get the newest update.
Then just hit the player to tag him and it should go back to normal.

**Comment by WilsonChoong** [comment]
I get it from craftbukkit and there is only 1 file for 1.17 spigot

**Comment by ChanceSD** [comment]
The proper way to get latest version is here: https://www.spigotmc.org/threads/spigot-bungeecord-1-17.510208/ with BuildTools
But if you want the easy way just google Spigot download or something like that.

**Comment by WilsonChoong** [comment]
ok i will try thx
