### ISSUE TITLE
Permission "pvpmanager.list" not working

### ISSUE THREAD

**Issue by ThatOverPowered** [ChanceSD/PvPManager#267]
**Describe the bug**
When giving a player the permission "pvpmanager.list" so the command "/pvp list" will be avalible. The player will recibe the "Error_Permission" message.

**To Reproduce**
1. Give to the player the "pvpmanager.list" node
2. As player, use the command "/pvp list"
3. You won't be able to use the command

**Expected behavior**
Player should be able to use the command since it have the right permission to do so

**Plugin and Server version**
PvP-Manager: 3.8.4
Server: git-Paper-209 (MC: 1.17.1)

**Additional context**
The server is running on Java 16 under a Ubuntu/Linux machine

**Comment by andris155** [comment]
Use the /pvplist command.
