### ISSUE TITLE
Doesn't prevent damage from ExcellentEnchants

### ISSUE THREAD

**Issue by Bloodlex** [ChanceSD/PvPManager#268]
**Describe the bug**
PVP is disabled in PVP manager, but some enchantments from [ExcellentEnchants](https://www.spigotmc.org/resources/excellentenchants-vanilla-like-enchantments-1-15-1-17.61693/) still do some damage... could you please help with that and prevent it? It occurs for instance in Withered Arrows or Bomber enchant.

**To Reproduce**
1. Install PVPManager and ExcellentEnchants
2. Get another player with turned off PVP in PVPManager
3. Use weapon with Withered Arrows or Bomber on this another player and it still could do damage

**Expected behavior**
Any damage should be prevented.

**Plugin and Server version**
PvpManager: 3.8.4
Server version: Purpur version git-Purpur-1060 (MC: 1.16.5)

**Comment by ChanceSD** [comment]
Issues like this usually need to be solved from the enchant plugin's side. Most likely by calling a damage event and check if it's cancelled by pvpmanager (or other protection plugins)
I'm open to make changes if I'm wrong and there's something to be done from my side though.
