### ISSUE TITLE
I AM STUCK IN VOID. I DONT KNOW WHAT TO DO

### ISSUE THREAD

**Issue by Strandkoffer** [ChanceSD/PvPManager#271]
**Describe the bug**
I trried on purpose to pvp log, When I came back I am stuck in the void. Can not use any commands or talk it says chat is disabled. I tried deleting my userdata and saw in the beginning that I could click on respawn but Its like 0,5 seconds. The world kinda exists and doesnt, Worldborder is there and other players are fine, But my account is not.

Pvplog.

**Plugin and Server version**
Second last version. I cant see now because I cant use commands. 

![image](https://user-images.githubusercontent.com/93754086/141667345-7750ea95-2e73-4504-a3dc-7bbb56b2ed78.png)

**Comment by ChanceSD** [comment]
The solution for chat is in the message, enable it in minecraft options, nothing to do with this plugin as it can't disable that.  
As for being in void, if you deleted your playerfile in the world folder and you still spawn there, it's also something else. PvPManager doesnt change your respawn location.
