### ISSUE TITLE
HEX colors

### ISSUE THREAD

**Issue by arteffAA** [ChanceSD/PvPManager#278]
It is worth adding the ability to support HEX colors

**Comment by youmpers** [comment]
Hi poovar. Goodbye

**Comment by youmpers** [comment]
I fully support the idea. I would like to see this added.

**Comment by youmpers** [comment]
I like the idea, Because this has been missing for a long time

**Comment by SevenToid** [comment]
I like this idea😁

**Comment by ChanceSD** [comment]
Alright, will add this, I'm not sure what format most plugins decided on though, I guess &#XXXXXX right?

**Comment by arteffAA** [comment]
Yes, DeluxMenus uses this format, thanks for noticing, because the plugin is great, its only drawback is the lack of Hex colors

**Comment by ChanceSD** [comment]
It seems to be working fine for me but if anyone else wants to test it: https://ci.codemc.io/job/ChanceSD/job/PvPManager/76/

**Comment by arteffAA** [comment]
Sorry for the long answer, everything works fine, thanks!
