### ISSUE TITLE
Autodisable PvP when disconnecting, changing world etc.

### ISSUE THREAD

**Issue by Villmarksjenta** [ChanceSD/PvPManager#286]
I am still new to using this plugin, so I am very sorry if this is already existing. But I would like to have the possibility to have the plugin auto disable PvP when a player relogs, change world, tp etc. To prevent any shady PvP strategies.

**Comment by ChanceSD** [comment]
I know it's pretty late but "pvpmanager.nopvp" should now do this on latest update.
Players with that permission get pvp disabled on login and when they change world.

**Comment by Villmarksjenta** [comment]
Thank you for this permission
