### ISSUE TITLE
Channeling Bypass

### ISSUE THREAD

**Issue by BrandonT80** [ChanceSD/PvPManager#293]
**Describe the bug**
Channeling enchant bypasses pvpmanager and kills players with pvp disabled

**To Reproduce**
1. Apply channeling to a trident
2. Throw trident at a player with pvp off
3. Player will take lightning damage

**Expected behavior**
Block the damage or hit to the player

**Plugin and Server version**
Use '/ver PvPManager' and '/ver' to get both versions
3.9.4
This server is running Paper version git-Paper-303 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 0f8aa4e)

**Comment by ChanceSD** [comment]
Thank you for the report, should protect players against lightining now
