### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by Insidi0usAngel** [ChanceSD/PvPManager#294]
10.05 08:08:27 [Server]  [PvPManager] The updater could not contact dev.bukkit.org for updating.
10.05 08:08:27 [Server]  [PvPManager] If you have not recently modified your configuration and this is the first time you are seeing this message, the site may be experiencing temporary downtime.
10.05 08:08:27 [Server]  java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.curseforge.com/servermods/files?projectIds=63773
10.05 08:08:27 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1985)
10.05 08:08:27 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
10.05 08:08:27 [Server]  at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
10.05 08:08:27 [Server]  at PvPManager.jar//me.NoChance.PvPManager.Libraries.Updater.BukkitUpdater.read(BukkitUpdater.java:73)
10.05 08:08:27 [Server]  at PvPManager.jar//me.NoChance.PvPManager.Libraries.Updater.Updater.runUpdater(Updater.java:55)
10.05 08:08:27 [Server]  at PvPManager.jar//me.NoChance.PvPManager.Libraries.Updater.Updater$1.run(Updater.java:44)
10.05 08:08:27 [Server] INFO [PvPManager] No update found

**Plugin and Server version**
Latest paper server, pvp manager 3.9.4

It looks as though its looking for an update but not finding one, not sure if this is that much of an issue/minor issue.

**Comment by ChanceSD** [comment]
This can be ignored, the curseforge API to check for updates probably had some temporary issue
