### ISSUE TITLE
A player can enter a protected zone when in combat

### ISSUE THREAD

**Issue by Animationking11** [ChanceSD/PvPManager#300]
**Describe the bug**
You can enter protected areas when in combat

**To Reproduce**
1. Use an elytra and fireworks to forcefully enter a protected zone (more in the video)

**Expected behavior**
If both players (with combat tag) enter the protected zone they can pvp even if in the zone pvp is enabled, This would be fixed if you fixed forcefully entering with fireworks so that's why I am reporting the entering part.

**Plugin and Server version**
PvPManager: 3.9.4
Server: Paper get-Paper-"af3b377"

**Screenshots/Video**
Video of me preforming the bug: https://www.youtube.com/watch?v=1P02lkirA_U

**Comment by ChanceSD** [comment]
This issue should be improved/solved in latest build https://ci.codemc.io/job/ChanceSD/job/PvPManager/
