### ISSUE TITLE
Bungeecord "Team [...] already exists in this scoreboard" Exception

### ISSUE THREAD

**Issue by Strafee** [ChanceSD/PvPManager#301]
**Describe the bug**
In a Bungeecord instance, when connecting from a server that does not have PvPManager to one that does, there's a chance that everyone will get disconnected from the server with PvPManager back to a fallback. The exception generated in the Bungeecord console/logs is "java.lang.IllegalArgumentException: Team PVP-581d817fd4fd already exists in this scoreboard" (or whatever UUID snippet of the player that joined). I say chance because this does not happen every time a player joins the server where PvPManager is installed but seems like it happens when a player changes their PvP status and then re-logs, causing the exception.

**To Reproduce**
1. Setup a Bungeecord instance with two servers, one with PvPManager installed and one as a fallback/lobby.
2. Connect to the server where PvPManager is installed.
3. Toggle PvP status and go back to the fallback server
4. Re-connect to the server where PvPManager is installed
5. See error (hopefully)...

**Expected behavior**
I did not expect all the players to get kicked off the server into the fallback. The server where PvPManager is installed kicks everyone and players are sent to a fallback server.

**Plugin and Server version**
Waterfall 1.19 (Git: c10f289)
Paper 1.19 (Git: 4c9317c)
PvPManager version 3.9.4

**Screenshots**
Not a screenshot, but the exception log. Will be happy to provide more logs and configs if needed.
https://www.toptal.com/developers/hastebin/bilanemeya.properties
This is my config:
https://www.toptal.com/developers/hastebin/vulofaqobo.yaml

**Additional context**
When I had PvP disabled, left the server, and joined back during my testing, I did not get the exception. 
As soon as I enabled PvP, left the server, and joined back, the exception was generated and got disconnected from the server. When I joined the server again later, my PvP status was back to being disabled.

Apologies if I missed something or failed to explain it properly.

**Comment by CayeOficial** [comment]
Same problem here, but not all players got disconnected, hopefully ChanceSD can add a way to disable scoreboard registration or something that stops the problems with scoreboards

**Comment by ChanceSD** [comment]
![image](https://user-images.githubusercontent.com/5256215/175129177-8a5df12f-c46d-4f60-b4ff-9bc24b84a699.png)
Set those two options to an empty string '' it should no longer create teams

**Comment by Strafee** [comment]
> ![image](https://user-images.githubusercontent.com/5256215/175129177-8a5df12f-c46d-4f60-b4ff-9bc24b84a699.png) Set those two options to an empty string '' it should no longer create teams

This fixed it. Thanks a lot!
