### ISSUE TITLE
Force PVP permission node

### ISSUE THREAD

**Issue by Silvobi** [ChanceSD/PvPManager#303]
**Is your feature request related to a problem? Please describe.**
I Noticed that you cannot force player to have pvp on in certain dimensions.

**Describe the solution you'd like**
Add permission node pvpmanager.forcepvp that will force player to have pvp enable (works opposite to pvpmanager.nopvp)

**Comment by Ben-Kantor** [comment]
This would be very useful, I cannot use this plugin currently because I don't want to let players turn combat off.

**Comment by ChanceSD** [comment]
Agreed, I was considering doing that already, makes sense and allows more configuration.

@Ben-Kantor That's unrelated to this, you can do that already by not giving players permission to use the pvp command, they can't turn combat off by defaul.
