### ISSUE TITLE
Forced PvP Worlds

### ISSUE THREAD

**Issue by BobtheBob123456** [ChanceSD/PvPManager#311]
Hi Guys,
So one feature idea I have for this plugin is forced PvP worlds. These are worlds where PvP is enabled for all players no matter what.

How it would work is in the Configs, there would be an area to list Forced PvP worlds. 

Admins would list the worlds where they want PvP to be forced and in those worlds, PvP would be forced, and players with the permission would be unable to run /pvp to change their PvP state.

There could also be an option to make some world's where there is no PvP.

That is All,

**Comment by ChanceSD** [comment]
You should be able to do this with the latest update. I added the permission pvpmanager.forcepvp
With this permission players get PvP force enabled and you can add that permission only on specific worlds.
 It depends on your permissions plugin but I think all of them allow permissions per world.

**Comment by BobtheBob123456** [comment]
Oh, ok
