### ISSUE TITLE
deny commands in combat

### ISSUE THREAD

**Issue by Natura4208** [ChanceSD/PvPManager#312]
I'm new to use this plugin, this isn't a "bug" but I need some help.
I got this plugin on minehut server (for free) and I wanted to deny some commands that I made with skript I tried black commands on config. but It didn't work, people on combat just tp away with skript. Maybe I didn't see in config. but I searched for days and didn't find forums or something. Help!

**Comment by ChanceSD** [comment]
If you want to block only specific commands, make sure to set Whitelist to false if you didn't. 
Otherwise if it's whitelist true it will allow all commands in the list
![image](https://user-images.githubusercontent.com/5256215/185801790-fdc33a5e-b888-47c2-ab28-0cc1be7bd893.png)

**Comment by Natura4208** [comment]
tysm
