### ISSUE TITLE
pvp command

### ISSUE THREAD

**Issue by YrChen1001** [ChanceSD/PvPManager#315]
**Describe the bug**
can not toggle pvp.

**To Reproduce**
when player use command /pvp to toggle , and there will show error message (screenshots)

**Expected behavior**
how to fix it.

**Plugin and Server version**
![image](https://user-images.githubusercontent.com/99790174/187056121-99881d6b-f7e7-4dd6-9451-fdcb8d434314.png)
![image](https://user-images.githubusercontent.com/99790174/187056133-8f9ed194-08c9-4326-899e-7e2db239822a.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/99790174/187056139-48592a05-0bc8-4a4b-a3f4-d39aecd1c6e7.png)

**Comment by ChanceSD** [comment]
See if the new update helps, if it doesn't then try negating the permission pvpmanager.nopvp and pvpmanager.forcepvp
