### ISSUE TITLE
Username issue

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [ChanceSD/PvPManager#316]
**Describe the bug**
Usernames are not visible on top to other players unless you reload the plugin.

**To Reproduce**
1. Start the server with the plugin present
2. Teleport to another player , you do not see the username on top of his/her player head
3. use `/pvpmanager reload` 
4. Username reappears

**Expected behavior**
Usernames should be visible without having to reload the plugin

**Plugin and Server version**
  [Tue 09:15:40 INFO ] PvPManager version 3.10.6
  [Tue 09:15:40 INFO ] Allows Administrators To Change Their PvP Mechanics.
  [Tue 09:15:40 INFO ] Website: https://www.spigotmc.org/resources/pvpmanager-lite.845/
  [Tue 09:15:40 INFO ] Author: ChanceSD
  [Tue 09:15:42 INFO ] Checking version, please wait...
  [Tue 09:15:42 INFO ] This server is running Paper version git-Paper-132 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: a76998d)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-131 (MC: 1.19.2)

**Screenshots**

**Additional context**
N/A

**Comment by ChanceSD** [comment]
PvPManager might be making your usernames appear again(probably when it assigns a scoreboard team) but it's definitely not the cause of them disappearing, there's no such feature here. So try looking through your other plugins.

You can fully disable use of scoreboards by pvpmanager by setting "nametag prefix" and "color" to an empty string like this ''
