### ISSUE TITLE
Pvptag/ combat tag not working/ registering when in combat.

### ISSUE THREAD

**Issue by willgames11** [ChanceSD/PvPManager#317]
**Describe the bug**
pvp combat tagging is not being registered

**To Reproduce**
No reproducing is needed since it seems to be conflicting with some other plugin but no errors show up in console

**Expected behavior**
Can attack other players and such but when checking for tags, nothing shows next to username or shows in chat that combat logging is happening

**Plugin and Server version**
![image](https://user-images.githubusercontent.com/112725953/188220313-71d93b7b-1410-41b2-ba7a-cc0a1d19778a.png)
![image](https://user-images.githubusercontent.com/112725953/188220350-117925cc-bfc4-4c54-9948-da37ec43c7f8.png)

**Screenshots**
Current plugin list 
![image](https://user-images.githubusercontent.com/112725953/188220405-6d3c5631-c67c-4c1c-9133-6ecab6e0de5b.png)
config of combat tagging 
![image](https://user-images.githubusercontent.com/112725953/188220521-9e3187b0-d2ee-48de-ae28-c88f8968d308.png)

**Additional context**
Was working fine at one point. Not sure what happened or what plugin is interfering with it. It even hooks properly with other plugins but i checked it all and cant find them problem of whats causing the pvp error. 
![image](https://user-images.githubusercontent.com/112725953/188223077-befe364b-78a9-4b7e-bd73-2afddf1668f5.png)

**Comment by ChanceSD** [comment]
Probably a permissions issue, check if players have any exempt permission: https://github.com/ChanceSD/PvPManager/wiki/Permissions
More specifically pvpmanager.nocombat

**Comment by willgames11** [comment]
Yep, that was the problem thank you
