### ISSUE TITLE
Translation Don't Work

### ISSUE THREAD

**Issue by jugandomiguel** [ChanceSD/PvPManager#329]
I changed my config to es and don't change the language still in english

**To Reproduce**
Don't send any error

**Expected behavior**
I wanted him to change the language from English to Spanish 

**Plugin and Server version**
PVPManager: **3.10.9**
Server: **This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
You are running the latest version
Previous version: git-Paper-216 (MC: 1.18.1)**

**Screenshots**
![image](https://user-images.githubusercontent.com/73621705/190145660-23eece86-6a7c-4613-8393-adbb8b269bd6.png)
![image](https://user-images.githubusercontent.com/73621705/190146352-870213d5-da85-42ea-be99-6def086eb1ad.png)
![image](https://user-images.githubusercontent.com/73621705/190145933-45eacd3b-b775-4498-a114-af90f2afd3c1.png)

**Additional context**
Don't change all messages

**Comment by ChanceSD** [comment]
I tried changing from "en" to "es" in the config, then doing /pmr reload and it worked.
Do you mean the bug is that the new messages are in English? 
You could also delete the messages file and let it create a new one with all the Spanish messages

**Comment by jugandomiguel** [comment]
Ok

**Comment by jugandomiguel** [comment]
IT work ty
