### ISSUE TITLE
 Give money from the murdered to the one who killed

### ISSUE THREAD

**Issue by AyerYT** [ChanceSD/PvPManager#337]
Hello, is it possible to do something in the config where money-penalty so that 10% is taken from the deceased and they are given to the one who killed. money-penalty simply adds 10% from an existing balance.

**Comment by ChanceSD** [comment]
That's money steal, just enable it in config, it will take the value specified in money reward

**Comment by Dharuzz** [comment]
> That's money steal, just enable it in config, it will take the value specified in money reward

Yeah but... just as requested... can you make it so that the "stolen money" is from PENALTY or REWARD or BOTH?
Maybe set `Money Steal: penalty #penalty, reward, none, both` instead of true/false.
That way, the Killer should get what's stablished when killing another player.

**Comment by ChanceSD** [comment]
> > That's money steal, just enable it in config, it will take the value specified in money reward
> 
> Yeah but... just as requested... can you make it so that the "stolen money" is from PENALTY or REWARD or BOTH? Maybe set `Money Steal: penalty #penalty, reward, none, both` instead of true/false. That way, the Killer should get what's stablished when killing another player.

It already does what was requested, if reward is set as 0.1 and money steal is enabled it will take 10% of the victim.
