### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by daltonsbiscord** [ChanceSD/PvPManager#338]
So I was going through my config to change some settings, but it seems like some of it went missing? Anyway someone can tell me how many lines are suppose to be in the settings.yml? or send me the whole thing?

**Comment by ChanceSD** [comment]
https://github.com/ChanceSD/PvPManager/blob/master/PvPManager/src/main/resources/config.yml

**Comment by daltonsbiscord** [comment]
> https://github.com/ChanceSD/PvPManager/blob/master/PvPManager/src/main/resources/config.yml

Thank you, Now do you mind sending me the folder for messages? Seems like some of that got deleted too.

**Comment by ChanceSD** [comment]
https://github.com/ChanceSD/PvPManager/blob/master/PvPManager/src/main/resources/locale/messages.properties
But  you could also just delete those files and restart the server/reload the plugin, and it would regenerate them. Assuming you're fine with losing what you changed
