### ISSUE TITLE
Wrong Locale input stream

### ISSUE THREAD

**Issue by Epicnicity322** [ChanceSD/PvPManager#340]
**Describe the bug**
The Locale enum has PT_BR value pointing towards "messages_pt_br.properties", but the resource file included in the jar is named "messages_pt_BR.properties". (The same for zh_TW localed). When the plugin checks for the resource in Messages#checkChanges, it can't find an Input Stream with name "messages_pt_br.properties" because it has the wrong name.

**To Reproduce**
1. Set locale to pt_BR in config
2. Reload

**Additional context**
You can fix this by simply fixing the enum class Locale.

**Comment by ChanceSD** [comment]
Yes, I fixed it here already some time ago, if you don't mind using the SQL update: https://github.com/ChanceSD/PvPManager/pull/313
Will probably be merged into the main version soon
