### ISSUE TITLE
Place Holder Info

### ISSUE THREAD

**Issue by Poiio78** [ChanceSD/PvPManager#356]
Hey boys, recently I'm recreating a server inspired in Minecraft Extremo (a spanish minecraft serie), Is there any option to change the display of the placeholder? 
It says yes or no depending if it's activated or not, but can I change the word to Activated, Desactivated?

![image](https://user-images.githubusercontent.com/110970032/214941534-df7b78cb-aaeb-4f6d-b925-b08162ad143a.png)

**Comment by ChanceSD** [comment]
You can change it in Placeholderapi's config, under boolean section.
