### ISSUE TITLE
Kill on logout

### ISSUE THREAD

**Issue by VibhorSharma199** [ChanceSD/PvPManager#360]
So Bug Is that i already set it to false reloaded still it is not working everybody dying on logout
 

Tagged In Combat:
  Enabled: true
  Time: 10
  NameTag Prefix: '&4&lCombat '
  Color: '&c'
  Glowing: true
  Action Bar:
    Message: '&b&lCombat &a<barsLeft>&c<barsPassed> &e&l<time> &b[sec]'
    Symbol: ▊
    Total Bars: 20
  Self Tag: false
  Untag Enemy: false
  Block:
    EnderPearls: false
    ChorusFruits: true
    Teleport: true
    Place Blocks: false
    Interact: false
    Elytra: false
    Eat: false
    Commands:
      Enabled: true
      Whitelist: true
      Command List:
      - 'tell'
      - 'tag'
  Punishments:
    Punish On Kick: false
    Money Penalty: 0
    Log To File: true
    Kill on Logout:
      Enabled: false
      Player Drops:
        Inventory: true
        Experience: true
        Armor: true
    Commands On PvPLog:
    - 'announce &6[&8PvP&6]&c %p tried to escape combat and died!'

**Comment by VibhorSharma199** [comment]
fix pls my issue

**Comment by ChanceSD** [comment]
Check Griefprevention config, it's usually that plugin still killing players.
