### ISSUE TITLE
Compatability with CooldownsX

### ISSUE THREAD

**Issue by TomLewis** [ChanceSD/PvPManager#370]
**Is your feature request related to a problem? Please describe.**
I noticed you recently added ender pearl cooldowns for when PvP tagged, this is perfect additon, that I actually requested from CooldownsX back in 2020 and was denied as they wanted me to move to their CombatLogX which has a lot less features than PvPManager Premium which I use.
https://github.com/SirBlobman/CooldownsX/issues/3

Would it be possible for PvPManager to gain CooldownsX compatibility or just completely remove the need for CooldownsX by implementing those features inside PvPManager, I use CooldownsX for PvP related cooldowns, ENDER_PEARL, CHORUS_FRUIT, GOLDEN_APPLE, ENCHANTED_GOLDEN_APPLE etc.

Whats nice is its a blanket cooldown for anything, not rigid to specific items.

I bumped into a minor bug today, where the timer is working when PvP tagged, but the feedback messages im getting from a cooldown on Ender Pearl is bugged in CooldownsX, but PvPManager is managing the timer!

So I have a 5s enderpearl timer in CooldownsX for general cooldown and the 15s timer in PvPManager to prevent the escape during a PvP fight, which is exactly how I want it to work! Its just bugged feedback to the user! 

![2023-03-18_10 56 12](https://user-images.githubusercontent.com/144046/226102183-cfddd753-f479-4f46-95e1-6e6ab1bd633d.png)

**Describe the solution you'd like**
Compatibility with CooldownsX cooldowns, but for when PvP tagged, without requiring CombatLogX.

**Comment by ChanceSD** [comment]
I still plan to add a general cooldown for other items as well, but I'm not sure if I would have separate cooldowns for global and in combat. Feels like I would be extending this plugin's features a bit too much. But I'll get a better idea of how complex it would be when I work on that.

I suggest you remove the cooldown just for enderpearls in cooldownsX and leave the 15s one, or maybe removing the feedback message from cooldownsx if that is possible. That last one would probably be the best option but I imagine you would still need the feedback messages for your other items.

**Comment by ChanceSD** [comment]
Actually I decided to try and hook into cooldownsx and it now changes the cooldown in cooldownsx while in combat.
You will just have to specify which id in cooldowns.yml is the one for enderpearls.

**Comment by TomLewis** [comment]
Sorry just testing this now! It is updating the cooldown in cooldownsX which is great! Just need to solve the visuals with the action bar message, I opened a new ticket for that! https://github.com/ChanceSD/PvPManager/issues/384

So with the  `EnderPearl Cooldown: 15` I keep that enabled in PvP manager right, and that just updates the cooldown in CooldownsX?

**Comment by ChanceSD** [comment]
Yes, you still need to specify the cooldown in PvPManager, so it applies that cooldown and changes it in cooldownsx while in combat.  
After that, it just goes back to whatever is defined in cooldownsx
