### ISSUE TITLE
[Feature Request] End Crystal tag support

### ISSUE THREAD

**Issue by Pantera07** [ChanceSD/PvPManager#371]
**Is your feature request related to a problem? Please describe.**
I request the implementation of a feature that supports CPvP by handling End Crystal damage.

**Describe the solution you'd like**
When a player receives damage from an End Crystal, they should be tagged for PvP.

**Comment by ChanceSD** [comment]
This is already present in the premium version. I suppose I could copy that feature to this version since it's not very complex, but if I kept applying that way of thinking for every simple feature there would be no reason for a premium version, you know. I'll consider porting it here though.
