### ISSUE TITLE
MMOitems conflict

### ISSUE THREAD

**Issue by ferxsy** [ChanceSD/PvPManager#374]
**Describe the bug**
When using MMOItems, when dealing dmg, or using a ability, every hits summons PVP Blood.
When using MMOitems abilities, they conflict with some and they are being false detected or something, they dont work.

**To Reproduce**
1. just use a ability with default config lol
**Expected behavior**
Nothing, PM shouldnt interfer

**Plugin and Server version**
1.19.3, PM 3.10.9

**Comment by ChanceSD** [comment]
You will have to give me an example of an item with those issues so I can reproduce it.
I didn't know anything about mmoitems but I gave it a try and then created a musket, worked just fine with pvpmanager.

**Comment by ChanceSD** [comment]
I'm closing this, will reopen if there's more details
