### ISSUE TITLE
PVP not staying off

### ISSUE THREAD

**Issue by forgotmyaccount75** [ChanceSD/PvPManager#379]
When my players do /pvp off it protects them for 1 hit and sends the attacker the message that they are protected but when they are attacked again it allows them to be hit and killed.

**Expected behavior**
PVP manager to not allow players with PVP off to be hit

**Plugin and Server version**
PVPmanager is version 3.11
Server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
**Screenshots**
![Bug PVP manager](https://user-images.githubusercontent.com/130429913/231058302-71bee7e9-29d1-42d9-91d3-073302336248.png)
![Bug Pvp manager2](https://user-images.githubusercontent.com/130429913/231058318-748d1a9d-5d98-4559-a389-17a2c765cfca.png)

**Comment by ChanceSD** [comment]
See this: https://github.com/ChanceSD/PvPManager/wiki#i-have-pvp-disabled-but-can-still-pvp-why-is-that  
More specifically reason number 2

**Comment by forgotmyaccount75** [comment]
Thanks, that fixed it.
