### ISSUE TITLE
New Features and config changes

### ISSUE THREAD

**Issue by CheaterPolska** [ChanceSD/PvPManager#393]
**Add options in config when player have pvp off or newbie protection can't place blocks**
On my servers players with pvp off or newbie protection place cobwebs

**In config add option to set when player have combat log can't open enderchest/chest/shulkers and other things like this**
On my server players with combat log can put items to enderchest.

**In config add option to set when player have combat log can't use: dors/buttons/plates and other things like this**

**Comment by ChanceSD** [comment]
You can enable block interact and block place blocks in the config already. Not for newbies though so that would possible be added

**Comment by ChanceSD** [comment]
Added option to block newbies from placing blocks, the other things like blocking interaction with chests/etc are already present.
