### ISSUE TITLE
Suggestion: Listing who has PvP disabled

### ISSUE THREAD

**Issue by TomLewis** [ChanceSD/PvPManager#400]
**Is your feature request related to a problem? Please describe.**
A list command when you moved to a database, so we could list all players that had PvP disabled.
if an admin disables PvP on a player logs off, and nobody knows about it!
we can just list everyone that has PvP disabled as a means of clearning up anyone that got forgotten about

**Describe the solution you'd like**
`/pvp list`

Bonus points if we can click peolpe in the list to do actions like remove pvp disabled.

EDIT: just seen `/pvplist` exists, if this uses the database for all offline players this is fine!

**Comment by ChanceSD** [comment]
The `/pvplist` command now can be run with an offline argument, so `/pvplist offline` which will gather all players with PvP disabled.

They aren't clickable though, and you can't change the PvP of those players if they are offline, I will possibly leave those features for another time. But at least you'll be able to tell if there's anyone with PvP disabled that was forgotten.
It should also be on the premium version by next update.

**Comment by TomLewis** [comment]
Legand! 

Maybe we could setup the "projects" section in this Github to put in these extra "todo" tasks for later on, can also be tracked into version releases too for easy note taking and you can assign issues to them as a universal way to keep track of conversations issues and features etc

I even made myself a subdomain to quickly redirect me to my project page for my servers bits!

**Comment by ChanceSD** [comment]
I do have a v4.0 milestone, I think it's sort of like projects right? https://github.com/ChanceSD/PvPManager/milestone/1
Every issue still open is marked for the v4 milestone currently. Wouldn't mind using projects though.
