### ISSUE TITLE
PVP LogOut

### ISSUE THREAD

**Issue by Streety111** [ChanceSD/PvPManager#413]
Hello, does the plugin already have or will it be possible to prevent players who have been damaged from leaving the game, or who have hit themselves (are in PVP mode). It is not protection from auto-exit, but from manual exit? How does the auto-exit protection work, will it protect if the player has time to manually exit?

**Comment by ChanceSD** [comment]
It can punish players that disconnect while they are in combat, I'm not sure what you mean by auto exit vs manual exit
Like pressing the disconnect button vs lagging out or is it something else

**Comment by ChanceSD** [comment]
Most you can do is enable match kick reason here https://github.com/ChanceSD/PvPManager/blob/fd3499cfe009505a3ae0435e88416a435e1851ce/pvpmanager/src/main/resources/config.yml#L123-L126 and only put the reasons you want, they are the ones that show in the console when a player leaves the server.
