### ISSUE TITLE
not working auto newbie prot

### ISSUE THREAD

**Issue by nixongame** [ChanceSD/PvPManager#415]
so my newbie protection works only when i add it manualy and idk what to do

my version of plugin is 3.15

**Comment by ChanceSD** [comment]
It only activates automatically on the first time a player enters the server, so for existing players it won't activate unless you delete their player file in the world folder

**Comment by nixongame** [comment]
> It only activates automatically on the first time a player enters the server, so for existing players it won't activate unless you delete their player file in the world folder

thing is it does not activate even then

**Comment by ChanceSD** [comment]
has to be some issue with your server then, it's working for me and everyone else as far as I know
