### ISSUE TITLE
i need to disable pvpmanager in BedWars

### ISSUE THREAD

**Issue by smscentras** [ChanceSD/PvPManager#424]
I need to disable pvpmanager in BedWars, there is other war system. How to do that?

**Comment by ChanceSD** [comment]
World exclusions I guess
https://github.com/ChanceSD/PvPManager/blob/b845614ffa70b542c320fb30e0abb49bee7fcd12/pvpmanager/src/main/resources/config.yml#L35-L36

**Comment by smscentras** [comment]
i have all games in one world, but one game need to disable fighting style.

**Comment by ChanceSD** [comment]
Permissions then, pvpmanager.exempt or the other permissions under it https://github.com/ChanceSD/PvPManager/wiki/Permissions

**Comment by smscentras** [comment]
maybe there is region exempts?
that would be the best option, what do you think?

**Comment by ChanceSD** [comment]
I think the best option is have bedwars in another world, don't know how your server works but just makes more sense
But maybe this works  https://www.spigotmc.org/resources/worldguard-extra-flags.4823/ and use console command on entry/exit to give them permission

**Comment by smscentras** [comment]
flag "pvpmanager.sign" - activates PVPmanager to work in region, which is not have active PVPmanager, yes?

**Comment by ChanceSD** [comment]
Isn't that a permission? But no, that permission is for creating signs which no longer works

**Comment by smscentras** [comment]
maybe this plugin have permission, to work in region, which did not have active pvpManager?
i want to activate this plugin with flag in regions, where is need that.

**Comment by ChanceSD** [comment]
This is fixed I think, if you're the same person I talked to in discord
