### ISSUE TITLE
OP do not drop items

### ISSUE THREAD

**Issue by Zapry** [ChanceSD/PvPManager#435]
**Describe the bug**

**To Reproduce**
1. Give OP to an administrator
2. If he die, he will not drop items

**Expected behavior**
I think that OP players would have to drop items
**Plugin and Server version**
Use '/ver PvPManager' and '/ver' to get both versions
Pufferfish version git-Pufferfish-73 (MC: 1.19.4) | PvPManager version 3.15.9

**Screenshots**

**Additional context**

**Comment by ChanceSD** [comment]
Die where, when logging out in combat or just any death?
Don't think this is caused by this plugin, there is no special permission to have no drops on death
