### ISSUE TITLE
Suggestion: consensual PvP sessions via hit returns

### ISSUE THREAD

**Issue by quiquelhappy** [ChanceSD/PvPManager#436]
Can you add an option to make a pvp session start when:
- a player hits another player (no damage taken)
- the player that was hit, hits the player back (no damage taken)
-> the pvp session starts, damage taken from this point on

I feel like it is a very intuitive way of starting a pvp session that makes it consensual

**Comment by ChanceSD** [comment]
I already gave a short reply on spigot but explaining a bit more here
I feel it would be cleaner to use a duel plugin for that. 
You could have pvp disabled for all players, and then they just use /duel when they want to fight. 
The Duels plugin has support for PvPManager afaik, so all you probably need is to drop it in
