### ISSUE TITLE
After you kill someone, you can't combat tag them ever again - you can't hit them etc

### ISSUE THREAD

**Issue by DHUO0** [ChanceSD/PvPManager#437]
After you kill someone, you can't combat tag them ever again - you can't hit them etc. You can only override it for a short while when you do /pvpoveride. that's it

**Comment by ChanceSD** [comment]
Does it say anything in chat? If the damage is blocked by pvpmanager it should say why in chat
Could be another plugin protecting them if there's no chat message

**Comment by DHUO0** [comment]
worldguard?

**Comment by DHUO0** [comment]
ok

**Comment by DHUO0** [comment]
could world
=guard be blocking it/.

**Comment by ChanceSD** [comment]
How would I know? You're the one running the server, try it.
