### ISSUE TITLE
Block opening plugin menus

### ISSUE THREAD

**Issue by zLunarKnight** [ChanceSD/PvPManager#476]
Hello, I want to inform you that it does not block all the commands, specifically the menus, for example the /buy of buycraft does not block it although you can use it in combat and there is a blockhit bug when you use /buy in pvp, not specifically in pvp but it can be bugged and other menus that don't block are the deluxemenus ones, surely there are more, I just don't know about it, if they solve it it would be better!

**Comment by ChanceSD** [comment]
Hello, can you show your current config, you can send the entire config or just the part that blocks commands if you want.
Then I'll test it and try to fix it if needed. I do think /buy gets blocked with no problem but I will retest it just in case.

**Comment by ChanceSD** [comment]
Alright, so I tested it with BuycraftX and it's not possible to block the /buy command because of how badly coded that plugin is.
They just made it in a way that it can't be blocked...

However, if you update to the new Tebex plugin they made https://www.spigotmc.org/resources/tebex.114261/ it seems to block it fine on that one.

Not sure about DeluxeMenus yet though, still need to test that one.

**Comment by zLunarKnight** [comment]
OK, aqui te paso un menu de Warps

menu_title: '&e➥ &nMenú de Warps'
open_command:
    - warp
    - warps
    - ewarp
    - ewarps
    - lugares
size: 54
items:
  'CRISTALES2':
    material: STAINED_GLASS_PANE
    data: 11
    display_name: "&8&m                                                  "
    lore: 
      - ''
      - ' &fDiscord: &bdiscord.gg/mineworld'
      - ' &fTienda: &atienda.mineworld.com'
      - ''
      - '&8&m                                                  '
    slots:
    - 0
    - 4
    - 8
    - 45
    - 53
    left_click_commands:
      - '[sound] NOTE_PLING 10 10'
      - '[message] &8[&a☯&8] &7» &fSeleccione un Lugar para &aTelenstraportarse...'
    right_click_commands:
      - '[sound] NOTE_PLING 10 10'
      - '[message] &8[&a☯&8] &7» &fSeleccione un Lugar para &aTelenstraportarse...'
  'CRISTALES3':
    material: STAINED_GLASS_PANE
    data: 3
    display_name: "&8&m                                                  "
    lore: 
      - ''
      - ' &fDiscord: &bdiscord.gg/mineworld'
      - ' &fTienda: &atienda.mineworld.com'
      - ''
      - '&8&m                                                  '
    slots:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 17
    - 36
    - 44
    - 46
    - 52
    left_click_commands:
      - '[sound] NOTE_PLING 10 10'
      - '[message] &8[&a☯&8] &7» &fSeleccione un Lugar para &aTelenstraportarse...'
    right_click_commands:
      - '[sound] NOTE_PLING 10 10'
      - '[message] &8[&a☯&8] &7» &fSeleccione un Lugar para &aTelenstraportarse...'
  'DISCORD':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGQ0MjMzN2JlMGJkY2EyMTI4MDk3ZjFjNWJiMTEwOWU1YzYzM2MxNzkyNmFmNWZiNmZjMjAwMDAwMTFhZWI1MyJ9fX0=
    slot: 18
    display_name: "&8&m                                                  "
    lore: 
      - ''
      - ' &fMantente informado sobre todas las'
      - ' &fActualizaciones y eventos dentro'
      - ' &fdel servidor!'
      - ''
      - '&8&m                                                  '
    left_click_commands:
      - '[player] discord'
      - '[close]'
    right_click_commands:
      - '[player] discord'
      - '[close]'
  'TIENDA':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjE4YmYzNTYwY2M4ZDA0ODI3NDA2NGNkMDE0MjI1N2Y4YjlmMTI3YmMwNDQ0ZmE1NzExOGRlMzJlODhmMzBkYSJ9fX0=
    slot: 27
    display_name: "&8&m                                                  "
    lore: 
      - ''
      - ' &fApoya al servidor comprando algún'
      - ' &fproducto de la Tienda o donando'
      - ' &fpara seguir creciendo!'
      - ''
      - '&8&m                                                  '
    left_click_commands:
      - '[player] tienda'
      - '[close]'
    right_click_commands:
      - '[player] tienda'
      - '[close]'
  'Minapvp':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDU4ZGZhNzkzOTZmYzdhOTQ3NmU3YjcyNzhmNTAwNGU1MDBjMzBkZTNmNmVlMzEyY2NlZjYyYWQ2ZDE1MDdmMiJ9fX0=
    slot: 20
    display_name: "&8»&m                    &8[ &bMinaPvp &8]&m                    &8«"
    lore:
      - ''
      - '  &fLugar donde puedes ganar mas dinero'
      - '       &fMinando en esta mina de peligro!'
      - ''
      - '&a▸ ¡Haz click para dirigirte!'
    left_click_commands:
      - '[player] warp Minapvp'
      - '[sound] CLICK 10 10'
      - '[close]'
    right_click_commands:
      - '[player] warp Minapvp'
      - '[sound] CLICK 10 10'
      - '[close]'
  'Minas':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDllZjdhNjQ1NDE0ZTkzMzkxYjcxMzNlM2U4MDJiZmZiYjUwNThlMDQ2M2ViMDQ4MTg3Zjc3ZmM2NWRiMzc2ZiJ9fX0=
    slot: 21
    display_name: "&8»&m                    &8[ &bMinas &8]&m                    &8«"
    lore:
      - ''
      - '  &fMenú de todas las minas del servidor'
      - '           &fy forma de farmear dinero!'
      - ''
      - '&a▸ ¡Haz click para dirigirte!'
    left_click_commands:
      - '[openguimenu] MenuMinas'
      - '[message] &8[&a☯&8] &7» &fDirigiendote al Menú de minas!'
      - '[sound] CLICK 10 10'
      - '[close]'
    right_click_commands:
      - '[openguimenu] MenuMinas'
      - '[message] &8[&a☯&8] &7» &fDirigiendote al Menú de minas!'
      - '[sound] CLICK 10 10'
      - '[close]'
  'Parcelas':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODlmN2EwNGFjMzM0ZmNhZjYxOGRhOWU4NDFmMDNjMDBkNzQ5MDAyZGM1OTJmODU0MGVmOTUzNDQ0MmNlY2Y0MiJ9fX0=
    slot: 22
    display_name: "&8»&m                    &8[ &bParcelas &8]&m                    &8«"
    lore:
      - ''
      - '  &fCrea una area de proteccion y que nadie'
      - '     &ftenga acceso y guarda tus cosas ahi!'
      - ''
      - '&a▸ ¡Haz click para dirigirte!'
    left_click_commands:
      - '[player] warp PARCELAS'
      - '[sound] CLICK 10 10'
      - '[close]'
    right_click_commands:
      - '[player] warp PARCELAS'
      - '[sound] CLICK 10 10'
      - '[close]'
  'Crates':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTZkN2ZkYjUwZjE0YzczMWM3MjdiMGUwZDE4OWI2YTg3NDMxOWZjMGQ3OWM4YTA5OWFjZmM3N2M3YjJkOTE5NiJ9fX0=
    slot: 23
    display_name: "&8»&m                    &8[ &bCrates &8]&m                    &8«"
    lore:
      - ''
      - '  &fAbre tus Llaves dentro de este warp'
      - '        &fpara conseguir recompensas!'
      - ''
      - '&a▸ ¡Haz click para dirigirte!'
    left_click_commands:
      - '[player] warp CRATES'
      - '[sound] CLICK 10 10'
      - '[close]'
    right_click_commands:
      - '[player] warp CRATES'
      - '[sound] CLICK 10 10'
      - '[close]'
  'Tradeos':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODIyODJjNmJiODM0M2UwZjBkNjFlZTA3NDdkYWRhNzUzNDRmMzMyZTlmZjBhY2FhM2FkY2RmMDkzMjFkM2RkIn19fQ==
    slot: 24
    display_name: "&8»&m                    &8[ &bTradeos &8]&m                    &8«"
    lore:
      - ''
      - '  &fIntercambia objetos OP con los aldeanos'
      - '         &fdentro de este lugar y estar OP!'
      - ''
      - '&a▸ ¡Haz click para dirigirte!'
    left_click_commands:
      - '[player] warp TRADEOS'
      - '[sound] CLICK 10 10'
      - '[close]'
    right_click_commands:
      - '[player] warp TRADEOS'
      - '[sound] CLICK 10 10'
      - '[close]'
  'ZonaAfk':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzc0MDBlYTE5ZGJkODRmNzVjMzlhZDY4MjNhYzRlZjc4NmYzOWY0OGZjNmY4NDYwMjM2NmFjMjliODM3NDIyIn19fQ==
    slot: 29
    display_name: "&8»&m                    &8[ &bZona-AFK &8]&m                    &8«"
    lore:
      - ''
      - '  &fGana recompensas solo por estar AFK en'
      - '            &funa zona predetermianda!'
      - ''
      - '&a▸ ¡Haz click para dirigirte!'
    left_click_commands:
      - '[player] warp AFK'
      - '[sound] CLICK 10 10'
      - '[close]'
    right_click_commands:
      - '[player] warp AFK'
      - '[sound] CLICK 10 10'
      - '[close]'
  'Pvp':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjIwMWFlMWE4YTA0ZGY1MjY1NmY1ZTQ4MTNlMWZiY2Y5Nzg3N2RiYmZiYzQyNjhkMDQzMTZkNmY5Zjc1MyJ9fX0=
    slot: 30
    display_name: "&8»&m                    &8[ &bPvp &8]&m                    &8«"
    lore:
      - ''
      - '  &fSin preocupaciones de FPS en este lugar'
      - '     &fpodras hacer pvp con el minimo Lag!'
      - ''
      - '&a▸ ¡Haz click para dirigirte!'
    left_click_commands:
      - '[player] warp PVP'
      - '[sound] CLICK 10 10'
      - '[close]'
    right_click_commands:
      - '[player] warp PVP'
      - '[sound] CLICK 10 10'
      - '[close]'
  'Koths':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWM0MjVlYTljNGE0Y2JkMTIzYTlmZmQ0YTBiYTc0ODBlN2M1MTU0MjNkZDczMGZiOWZiNjQzYzE4NDkwMTA3ZiJ9fX0=
    slot: 31
    display_name: "&8»&m                    &8[ &bKOTHS &8]&m                    &8«"
    lore:
      - ''
      - '  &fCaptura el koth que esta dentro de una zona'
      - '          &fmarcada y ganaras recompensas!'
      - ''
      - '&a▸ ¡Haz click para dirigirte!'
    left_click_commands:
      - '[openguimenu] MenuKoths'
      - '[message] &8[&a☯&8] &7» &fDirigiendote al Menú de KOTHS!'
      - '[sound] CLICK 10 10'
      - '[close]'
    right_click_commands:
      - '[openguimenu] MenuKoths'
      - '[message] &8[&a☯&8] &7» &fDirigiendote al Menú de KOTHS!'
      - '[sound] CLICK 10 10'
      - '[close]'
  'Eventos':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTJmMDk2ZWVmODdkOWYyMGNjYWFiYTJhMDJlZWQ2ZjQzZTY0MzJhNjkyOGZlMTY0NjdjYjRkZWI1ZTc0MTE4YyJ9fX0=
    slot: 32
    display_name: "&8»&m                    &8[ &bEVENTOS &8]&m                    &8«"
    lore:
      - ''
      - '  &fEl warp donde se realizara los eventos del'
      - '        &fservidor, se anunciara por discord!'
      - ''
      - '&a▸ ¡Haz click para dirigirte!'
    left_click_commands:
      - '[player] warp EVENTOS'
      - '[sound] CLICK 10 10'
      - '[close]'
    right_click_commands:
      - '[player] warp EVENTOS'
      - '[sound] CLICK 10 10'
      - '[close]'
  'Bosses':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDY5Y2I4Y2VlMjU0NDU0MmNmMzUwYTc4MjcxMTE2MWY4MGQ2MTVlZDQ5OGI1YTYxNGY4ODA0ZGI2OTVmYzU0YyJ9fX0=
    slot: 33
    display_name: "&8»&m                    &8[ &bBOSSES &8]&m                    &8«"
    lore:
      - ''
      - '  &fUsa tus habilidades de lucha en este lugar para'
      - '         &fmatar jefes y obtener recompensas!'
      - ''
      - '&7BOSSES: &c&nProximamente'
      - ''
      - '&a▸ ¡Haz click para dirigirte!'
    left_click_commands:
      - '[player] warp BOSSES'
      - '[sound] CLICK 10 10'
      - '[close]'
    right_click_commands:
      - '[player] warp BOSSES'
      - '[sound] CLICK 10 10'
      - '[close]'
  'MinaPrivada':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGUwN2ViYzIzOTMzZGZlZGI2MDIwYjE0NjQ5ZmVlMzg5Njg4MjY5Yzk4NTQ4OTA5NGY4MGI2MzkzYzY5MWNhOCJ9fX0=
    slot: 48
    display_name: "&8»&m                    &8[ &bProximamente &8]&m                    &8«"
    lore:
      - ''
      - '  &fNo hay ningun destino en este momento...'
      - ''
      - '&a▸ ¡Haz click para dirigirte!'
    left_click_commands:
      - '[message] &8[&a☯&8] &7» &fEsto todavia no esta creado...'
      - '[sound] CLICK 10 10'
      - '[close]'
    right_click_commands:
      - '[message] &8[&a☯&8] &7» &fEsto todavia no esta creado...'
      - '[sound] CLICK 10 10'
      - '[close]'
  'spawn':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODU5NjhiNjE2MGYzODBmYmU3ODY5YTMwNzBlYjdmYjc2MjY3ZGIwN2Q2ODRlYzIwZjdlOThjMWQwNzNkZDcwMiJ9fX0=
    slot: 49
    display_name: "&8»&m                    &8[ &bSpawn &8]&m                    &8«"
    lore:
      - ''
      - '  &f¡Vuelve al lugar del inicio del servidor!'
      - ''
      - '&a▸ ¡Haz click para dirigirte!'
    left_click_commands:
      - '[player] spawn'
      - '[sound] CLICK 10 10'
      - '[close]'
    right_click_commands:
      - '[player] spawn'
      - '[sound] CLICK 10 10'
      - '[close]'
  'proximamente':
    material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWRkYTJlODJkMDA5ZWE4MzA1NTE2ZGRhYjFhMzllMDFkN2FhNDZkMDkyOTJiMzA4MDY2ZTVlN2UwNDg2YzU3MiJ9fX0=
    slot: 50
    display_name: "&8»&m                    &8[ &bProximamente &8]&m                    &8«"
    lore:
      - ''
      - '  &fNo hay ningun destino en este momento...'
      - ''
      - '&a▸ ¡Haz click para dirigirte!'
    left_click_commands:
      - '[message] &8[&a☯&8] &7» &fEsto todavia no esta creado...'
      - '[sound] CLICK 10 10'
      - '[close]'
    right_click_commands:
      - '[message] &8[&a☯&8] &7» &fEsto todavia no esta creado...'
      - '[sound] CLICK 10 10'
      - '[close]'

**Comment by zLunarKnight** [comment]
Vale, aqui te paso un menu de warps

[https://mclo.gs/M8b9g0z](url)

**Comment by zLunarKnight** [comment]
El comando de /buy tal vez se pueda bloquear cuando el jugador ejecute el comando en combate y le cierre el menu al instante o cualquier menu se cierre cuando lo utilizas en combate.

**Comment by ChanceSD** [comment]
Oh I guess I can just block inventories from opening instead of only blocking the commands sure, will probably add an option for that then.

**Comment by ChanceSD** [comment]
Try this build please, it should block opening menus while in combat: https://ci.codemc.io/job/ChanceSD/job/PvPManager/317/

**Comment by ChanceSD** [comment]
@zLunarKnight Just in case you didn't see, sorry if you already did.

**Comment by ChanceSD** [comment]
Well I'm gonna assume this is solved.
