### ISSUE TITLE
Add info about placeholders in description

### ISSUE THREAD

**Issue by Dromaeosaurs** [ChanceSD/PvPManager#485]
**Is your feature request related to a problem? Please describe.**

1. I'm pretty sure that some people check if a plugin has placeholders only via papi wiki or plugin descripitons.
There's no information about that in both of them

**Describe the solution you'd like**

1. Add something alongside of: "This plugin also has placeholders! Type /papi info pvpmanager" in the plugin's description on spigot

**Comment by ChanceSD** [comment]
Good point, I don't browse many other plugins so this is a helpful suggestion.
Do other plugins have a list of all their placeholders on the spigot page? Would probably be a bit much since it would be all of these https://github.com/ChanceSD/PvPManager/wiki/PlaceHolderAPI

**Comment by ChanceSD** [comment]
Wait, actually I was just looking at the spigot page and it does have a link to the placeholders 
![image](https://github.com/ChanceSD/PvPManager/assets/5256215/611e1a95-5e59-4756-8e98-068ce4d9b25f)
Maybe it's not very visible and should put it somewhere else

**Comment by ChanceSD** [comment]
I don't want to close this yet, still want it as a reminder to add an entry to placeholder's api wiki.

**Comment by ChanceSD** [comment]
Ok I made a pull request to PlaceholderAPI's wiki, now just waiting for them to approve it. Thanks for the suggestion!
