### ISSUE TITLE
Not getting pushed enough from no-pvp zones

### ISSUE THREAD

**Issue by unnamed199cz** [ChanceSD/PvPManager#500]
### Describe the bug
Randomly players (prolly based on bad ping) wont get pushed enough from claimed area when they are pvp tagged while having netherite armor, the combination of knockback resistance and their ping (prolly) makes them able to go into those areas, i think there is some way to make it impossible

### Plugin and Server version
3.18.11
![image](https://github.com/ChanceSD/PvPManager/assets/69002814/8a94e8da-4245-41c8-bbc8-26a3a0530747)

**Comment by ChanceSD** [comment]
This and the enderpearl issue have been handled in the premium version for a long time. For the free version it will also be corrected in v4.0, see https://github.com/ChanceSD/PvPManager/pull/376, although even if you know how to compile it there are still some issues since it's unfinished.

**Comment by ChanceSD** [comment]
If you or anyone needs this there are now dev builds for: v4 https://github.com/ChanceSD/PvPManager/pull/376
Although anyone using it will need to delete their messages and config file, and it's very early builds so might have a few bugs.
