### ISSUE TITLE
Enderpearl bypasses push from claimed location

### ISSUE THREAD

**Issue by unnamed199cz** [ChanceSD/PvPManager#501]
### Describe the bug
Enderpearl bypasses push from claimed location
you in pvp
you teleport with pearl
you dont get pushed and are free to go into any claimed area

### Plugin and Server version
PvPManager v3.18.11
![image](https://github.com/ChanceSD/PvPManager/assets/69002814/80d4ade0-5bc6-48de-b6f3-fc1e76f396cf)

**Comment by ChanceSD** [comment]
Replied here https://github.com/ChanceSD/PvPManager/issues/500#issuecomment-2146139520
