### ISSUE TITLE
TNT carts to kill players

### ISSUE THREAD

**Issue by IAMSOEPIC2303** [ChanceSD/PvPManager#502]

**Comment by IAMSOEPIC2303** [comment]
tnt carts kill players in disable pvp

**Comment by IAMSOEPIC2303** [comment]
im not gonna respond to this bci just wanted an acc to comment on the bug. please fix it

**Comment by IAMSOEPIC2303** [comment]
Why the hell remove from bugs. It’s a damn big. People abuse the damn mute carts to kill ppl

**Comment by ChanceSD** [comment]
Because it's not a bug.

**Comment by ChanceSD** [comment]
Won't be adding this to free version, it's already on premium since last year.
