### ISSUE TITLE
Reapply PvP Tag on Ender Pearl Usage

### ISSUE THREAD

**Issue by CoolManTheCool** [ChanceSD/PvPManager#503]
**Description:**

I've been encountering an issue on my SMP server where players can easily escape PvP combat by using ender pearls. This behavior disrupts the intended PvP experience, as players can immediately teleport away and avoid combat after initiating a fight.

**Current Behavior:**
- Players start a fight.
- Players use an ender pearl to teleport away.
- PvP tag is not reapplied, allowing them to escape combat without consequences.

**Proposed Solution:**
- Reapply the PvP tag to a player if an ender pearl is thrown and when it lands if the player is already tagged.
- This change will ensure that players cannot easily escape combat by using ender pearls.

**Benefits:**
- Enhances the PvP experience by preventing easy escapes.
- Maintains fairness in combat situations.
- Encourages players to commit to fights rather than avoiding them.

**Steps to Reproduce:**
1. Engage in PvP combat with another player.
2. The opposing player uses an ender pearl to teleport away.
3. Notice that the PvP tag is not reapplied.

**Expected Behavior:**
- When a player uses an ender pearl while PvP tagged, the PvP tag should be reapplied both when the pearl is thrown and when it lands, preventing them from escaping combat without consequences.

**Additional Context:**
This feature would be particularly useful in SMP servers where PvP engagements are common, and players often use ender pearls to avoid fights. Ensuring the PvP tag is reapplied on ender pearl usage will promote a more balanced and competitive environment.

Thank you for considering this enhancement. Looking forward to your response!

**Comment by ChanceSD** [comment]
Have you tried this https://github.com/ChanceSD/PvPManager/blob/579bef8fb9a539eff0e2b7b20b7c74abbdc52278/pvpmanager/src/main/resources/config.yml#L109

**Comment by ChanceSD** [comment]
This feature already exists as far as I know, let me know if not.

**Comment by CoolManTheCool** [comment]
Oh it works thanks

**Comment by ChanceSD** [comment]
Nice, I appreciate the detailed suggestion though! I wish there were more like it
