### ISSUE TITLE
Retag player after combat log

### ISSUE THREAD

**Issue by TheFaik** [ChanceSD/PvPManager#504]
Hello! I would like to suggest a small improvement. I use your plugin to block teleportation commands in PVP, but I encountered such a problem, namely, the disappearance of the PVP mode after the player re-enters the server, so I ask you to introduce a function to leave the PVP mode after leaving the server until he re-enters and the PVP mode timer passes. I would be very grateful if you add it) Thank you for your attention. (Translated using Google Translate from Russian to English)

**Comment by ChanceSD** [comment]
But the point of the combat timer is to prevent combat logouts, when the player logs out and gets punished the timer goes away.
Not sure if it makes much sense to put the player in combat again when they log back in.

**Comment by TheFaik** [comment]
Yes, I understand, but why not. There are a lot of people, so there will be those who need it, for example me)
You can even do this in the premium version, I don't mind.

**Comment by TheFaik** [comment]
i didn't really mean creating NPC after leaving the server, actually i meant that the time that was left after the player left, was returned to him again when he reconnected to the server. I guess you didn't understand because of Google Translate... But thanks for making the update in such a short time, but i would like to add what i described above, i can rephrase if you don't understand again :)

**Comment by TheFaik** [comment]
I use your plugin to block teleportation commands during PVP players, that is, I add commands to the whitelist that can be used. And those that cannot, I simply do not enter, BUT the problem is that the PVP mode disappears after the player leaves and re-enters the server.

**Comment by ChanceSD** [comment]
> i didn't really mean creating NPC after leaving the server, actually i meant that the time that was left after the player left, was returned to him again when he reconnected to the server. I guess you didn't understand because of Google Translate... But thanks for making the update in such a short time, but i would like to add what i described above, i can rephrase if you don't understand again :)

What, I didn't make any update about this. And I thought you were using the free version.
Also, if you're using the premium version it already has this feature, if the player logs in while an NPC is spawned they will be tagged in combat again. Only block login needs to be false.

**Comment by TheFaik** [comment]
Is it possible to do it without NPC?

> > На самом деле я не имел в виду создание NPC после ухода с сервера, на самом деле я имел в виду, что время, оставшееся после ухода игрока, возвращалось ему снова при повторном подключении к серверу.  Я думаю, вы не поняли из-за Google Translate... Но спасибо, что сделали обновление за такое короткое время, но я хотел бы добавить то, что описал выше, могу перефразировать, если вы снова не поняли :)
> 
> Что, я не делал никаких обновлений по этому поводу. А я думал ты используешь бесплатную версию. Кроме того, если вы используете премиум-версию, в ней уже есть эта функция: если игрок войдет в систему во время появления NPC, он снова будет помечен в бою. Только блокировать вход в систему должно быть ложным.

**Comment by TheFaik** [comment]
@ChanceSD 

> Is it possible to do it without NPC?
> 
> > > На самом деле я не имел в виду создание NPC после ухода с сервера, на самом деле я имел в виду, что время, оставшееся после ухода игрока, возвращалось ему снова при повторном подключении к серверу.  Я думаю, вы не поняли из-за Google Translate... Но спасибо, что сделали обновление за такое короткое время, но я хотел бы добавить то, что описал выше, могу перефразировать, если вы снова не поняли :)
> > 
> > 
> > Что, я не делал никаких обновлений по этому поводу. А я думал ты используешь бесплатную версию. Кроме того, если вы используете премиум-версию, в ней уже есть эта функция: если игрок войдет в систему во время появления NPC, он снова будет помечен в бою. Только блокировать вход в систему должно быть ложным.
