### ISSUE TITLE
Can execute CustomCommands while tagged in pvp

### ISSUE THREAD

**Issue by XPaladiumyX** [ChanceSD/PvPManager#507]
### Describe the bug
So, i use a plugin to create custom command named CustomCommands made by GuillaumeVDN
And theses commands can still be executed while tagged in PVP, i just wanted to report this bug cause peoples can literally flee in 
a mid of pvp.

### To reproduce the bug
Create a command who have the ability to tp with CustomCommands Plugins
1. Execute any command with CustomCommands plugins
2. Went in a pvp with somone to be tagged
3. Execute the command and it works.

### Plugin and Server version
Latest Version PvpManager and CustomsCommands Plugins
Server Version Paper 1.20.1

**Comment by ChanceSD** [comment]
The commands need to be executed as if they were run by the player, I don't know how that plugin works but if they make the commands run through console then they won't be blocked.
