### ISSUE TITLE
Crash server (ShreddedPaper)

### ISSUE THREAD

**Issue by kitovoi111** [ChanceSD/PvPManager#520]
Crash server (ShreddedPaper)

Please fix this error https://mclo.gs/4bOnNkc
Core: https://github.com/MultiPaper/ShreddedPaper
Version 1.20.6

**Comment by ChanceSD** [comment]
That's mostly caused by that unsupported fork, with Folia that likely wouldn't happen.
But set `Nametag prefix` to empty in config, that will disable scoreboard teams for pvpmanager and the error shouldn't happen anymore.
Or upgrade to premium version or pvpmanager lite v4.0
