### ISSUE TITLE
Combat stays after pvp end, unable to reload

### ISSUE THREAD

**Issue by unnamed199cz** [ChanceSD/PvPManager#522]
### Describe the bug
pvp timer is not showing
people stay in combat after timer ends
pmr reload does not work 2 times then its working (error as screenshot sent)

### To reproduce the bug
not sure, just time destroyed it? We had the issues, we restarted the server, it vanished, and after while we have the issues again

### Plugin and Server version
[14:02:42 INFO]: Checking version, please wait...
[14:02:42 INFO]: This server is running Paper version 1.21-124-master@df3b654 (2024-08-02T00:02:38Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-109-5a5035b (MC: 1.21)

[14:02:59 INFO]: PvPManager version 3.18.18
[14:02:59 INFO]: A powerful plugin to manage various PvP combat features
[14:02:59 INFO]: Website: https://www.spigotmc.org/resources/pvpmanager-lite.845/
[14:02:59 INFO]: Author: ChanceSD

### Screenshots
![image](https://github.com/user-attachments/assets/3bb3aff3-5583-4b40-afb5-952b47ea784c)

**Comment by ChanceSD** [comment]
There has to be another error earlier in the logs, at some point since the server started.
I need that error to be able to tell what happened.
Also the error in screenshot is also cut at the part that would be relevant, the lines after `caused by` would provide more details.

**Comment by unnamed199cz** [comment]
![image](https://github.com/user-attachments/assets/bfdd3cbe-efe7-4772-80ae-0523bc189fc5)
![image](https://github.com/user-attachments/assets/13604ac3-4e16-416b-a335-661c44c54f9f)

this is all i get

**Comment by ChanceSD** [comment]
Look in your console log files or put them here https://mclo.gs/

**Comment by unnamed199cz** [comment]
https://mclo.gs/b0wv0r4

**Comment by ChanceSD** [comment]
![image](https://github.com/user-attachments/assets/896a89a2-87c8-4ba4-869e-7fbf265f70c7)
This is where the timer stops working, but your server seems to be cutting the error traces or something, not sure why.
I can't identify what's causing it like this, since it doesn't show the lines of code.

**Comment by unnamed199cz** [comment]
So i cannot do anything about it?

**Comment by ChanceSD** [comment]
Try this build, hopefully it will print more info when it happens again https://ci.codemc.io/job/ChanceSD/job/PvPManager/395/

**Comment by unnamed199cz** [comment]
![image](https://github.com/user-attachments/assets/474cf570-4153-4933-9062-edbd20fde5ee)
https://mclo.gs/gFXRyJ9#L1660

**Comment by ChanceSD** [comment]
Alright, so there's different solutions for this issue:

- Set `Nametag Prefix` in config to an empty string like this: ''
- Use PvPManager premium or the free v4 version which uses TAB for nametags and avoids this issue
- Try this new dev build if you want to help in further debugging https://ci.codemc.io/job/ChanceSD/job/PvPManager/396/

First one is probably the easiest, and should fully solve the issue as PvPManager will no longer use minecraft teams.

**Comment by unnamed199cz** [comment]
https://mclo.gs/Z3iUTSC

**Comment by ChanceSD** [comment]
> https://mclo.gs/Z3iUTSC

That's with solution 1 right? Sorry I assumed you had pvp toggle nametags already disabled
![image](https://github.com/user-attachments/assets/29e8b6ad-901d-4916-9b5a-c04002748d26)
You will need to have this one set to false as well

**Comment by unnamed199cz** [comment]
it was both solution 1 and 3, ill try this new thing

**Comment by ChanceSD** [comment]
> it was both solution 1 and 3, ill try this new thing
> 
> also, why nametags have to be disabled, and is there a way it could be enabled in future?

Because with TAB enabled, other plugins can't change nametags, unless they hook into TAB.
And the TAB hook is currently only on premium PvPManager and will be in free version in the future when v4 is out of beta.
