### ISSUE TITLE
Combat timer is glich out

### ISSUE THREAD

**Issue by SkeloD** [ChanceSD/PvPManager#525]
### Description
When players are attacked its all normal but when they leave they get combat log

### Plugin and Server version
Server:
This server is running Custom-Server version git-customserver-156 (MC: 1.18)
[15:06:25 INFO]: (Implementing API version 1.18-SNAPSHOT)

Plugin: it is using the latest version

log error
[14:58:41 ERROR]: Could not pass event PlayerQuitEvent to PvPManager v3.18.21
java.lang.ArrayIndexOutOfBoundsException: null

**Comment by ChanceSD** [comment]
Check for early errors before that happened, since server started. Or put the console log here, it will hide player IPs https://mclo.gs/ and share it here so I can check.
