### ISSUE TITLE
pvpmanager plugin not loaded

### ISSUE THREAD

**Issue by ItsCody04** [ChanceSD/PvPManager#526]
purple 1.20
plugin  lastest version

https://mclo.gs/HlTeZEe

**Comment by Barpadzik** [comment]
Why using 1.20? It has bugs, use > 1.20.4 | 1.20.6 | 1.21.1

**Comment by ChanceSD** [comment]
Probably the maven repository website was having some downtime or something similar, they should resolve it if it already isn't.
