### ISSUE TITLE
Database console spam

### ISSUE THREAD

**Issue by Henriiig** [ChanceSD/PvPManager#533]
How do I turn off the use the database. I have set "log to file" to false and get this spam

https://pastebin.com/8BQse7cV

**Comment by ChanceSD** [comment]
It always uses a database, either sqlite which is just a file database.db or mysql. Seems like an issue with sqlite on 1.8, can you switch to mysql in config? If you're using a server host you should have one available, most likely will solve the issue

**Comment by Henriiig** [comment]
Looks like it was somehow fixed after restart but I remember that I also experienced a similar problem with sqlite for playerparticles. So I switched to using mysql for both now. Thanks anyways.
